// <auto-generated />
using System;
using FamilyMoneyManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyMoneyManagementSystem.Migrations
{
    [DbContext(typeof(MoneySystemDbContext))]
    partial class MoneySystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamilyMoneyManagementSystem.Models.Money.MoneyTax", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("Username");

                    b.ToTable("Money");
                });

            modelBuilder.Entity("FamilyMoneyManagementSystem.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(250)");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FamilyMoneyManagementSystem.Models.Money.MoneyTax", b =>
                {
                    b.HasOne("FamilyMoneyManagementSystem.Models.User", "User")
                        .WithMany("Money")
                        .HasForeignKey("Username");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyMoneyManagementSystem.Models.User", b =>
                {
                    b.Navigation("Money");
                });
#pragma warning restore 612, 618
        }
    }
}
